version: "3"

volumes:
  postgres11_data:
    driver: local
  bundle_cache:
    driver: local

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres11_data:/var/lib/postgresql/data
    logging:
      driver: "none"
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app:delegated
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - MALLARD_DATABASE_URL=postgres://postgres:postgres@postgres/mallard_development
      - MALLARD_DATABASE_URL_TEST=postgres://postgres:postgres@postgres/mallard_test
      - RACK_ENV=development
      - NODE_ENV=development
    command: ["rails", "server", "-b", "0.0.0.0"]
